### ISSUE TITLE
metadata_base.PrimitiveFamily.ANOMALY_DETECTION - MISSING PRIMITIVE ANOMALY_DETECTION

### ISSUE THREAD

**Issue by dynamite9999** [datamllab/tods#105]
I am wondering why metadata_base.PrimitiveFamily is missing ANOMALY_DETECTION ?

I did python setup.py build and install, as per README.
Any hints or clues greatly appreciated.

I tried to run the simple examples, and they all fail on the same issue:
python LOF_pipeline.py 
Traceback (most recent call last):
  File "LOF_pipeline.py", line 11, in <module>
    primitive_0 = index.get_primitive('d3m.primitives.tods.data_processing.dataset_to_dataframe')
  File "/home/d/miniconda3/envs/anomalytods/lib/python3.7/site-packages/d3m/index.py", line 116, in get_primitive
    return getattr(module, name)
  File "/home/d/miniconda3/envs/anomalytods/lib/python3.7/site-packages/d3m/namespace.py", line 112, in __getattr__
    primitive = entry_point.resolve()
  File "/home/d/miniconda3/envs/anomalytods/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/d/miniconda3/envs/anomalytods/lib/python3.7/site-packages/tods-0.0.2-py3.7.egg/tods/__init__.py", line 1, in <module>
    from .utils import *
  File "/home/d/miniconda3/envs/anomalytods/lib/python3.7/site-packages/tods-0.0.2-py3.7.egg/tods/utils.py", line 30, in <module>
    'anomaly_detect': metadata_base.PrimitiveFamily.ANOMALY_DETECTION,
  File "/home/d/miniconda3/envs/anomalytods/lib/python3.7/enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: ANOMALY_DETECTION

**Comment by lhenry15** [comment]
Try pip uninstall d3m. Then do "pip install -e ." in tods/ again. Could be the wrong version of D3M.

**Comment by Pekary** [comment]
it seems python3.6 has no this problem.

**Comment by Martini-Chwang** [comment]
python 3.6 solves the ANOMALY DETECTION error, but a new error appears. setup.py requires 'ray[tune]>=1.13.0', however python 3.6 only has ray[tune] version up to 1.12.1. Is there a solution to this?
