### ISSUE TITLE
InvalidGitRepositoryError

### ISSUE THREAD

**Issue by xiashengjie** [datamllab/tods#111]
What should I do if I get the following error when running the sample file run_bruteforce_search.py?

Traceback (most recent call last):
  File "examples/axolotl_interface/run_bruteforce_search.py", line 5, in <module>
    from tods import generate_dataset, generate_problem
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/tods-0.0.2-py3.7.egg/tods/__init__.py", line 5, in <module>
    from tods.detection_algorithm import *
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/tods-0.0.2-py3.7.egg/tods/detection_algorithm/__init__.py", line 17, in <module>
    from tods.detection_algorithm.PyodMoGaal import Mo_GaalPrimitive
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/tods-0.0.2-py3.7.egg/tods/detection_algorithm/PyodMoGaal.py", line 126, in <module>
    class Mo_GaalPrimitive(UnsupervisedOutlierDetectorBase[Inputs, Outputs, Params, Hyperparams]):
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/tods-0.0.2-py3.7.egg/tods/detection_algorithm/PyodMoGaal.py", line 192, in Mo_GaalPrimitive
    git_commit=d3m_utils.current_git_commit(os.path.dirname(__file__)),
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/d3m/utils.py", line 95, in current_git_commit
    repo = git.Repo(path=path, search_parent_directories=search_parent_directories)
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/root/anaconda3/envs/xsj/lib/python3.7/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

**Comment by goodman233** [comment]
用ubuntu系统，按照readme说的步骤，一步一步配置就可以使用，我配了三次，最后完全按照readme来成功运行了
