### ISSUE TITLE
AttributeError: ISOLATION_FOREST

### ISSUE THREAD

**Issue by cdycdy666** [datamllab/tods#48]
when i run LSTMOD_test.py

Traceback (most recent call last):
  File "LSTMOD_test.py", line 2, in <module>
    from tods.sk_interface.detection_algorithm.LSTMODetector_skinterface import LSTMODetectorSKI
  File "/home/tods/tods/__init__.py", line 5, in <module>
    from tods.detection_algorithm import *
  File "/home/tods/tods/detection_algorithm/__init__.py", line 5, in <module>
    from tods.detection_algorithm.LSTMODetect import LSTMODetectorPrimitive
  File "/home/tods/tods/detection_algorithm/LSTMODetect.py", line 164, in <module>
    class LSTMODetectorPrimitive(UnsupervisedOutlierDetectorBase[Inputs, Outputs, Params, Hyperparams]):
  File "/home/tods/tods/detection_algorithm/LSTMODetect.py", line 199, in LSTMODetectorPrimitive
    "algorithm_types": [metadata_base.PrimitiveAlgorithmType.ISOLATION_FOREST, ], # up to update
  File "/home/anaconda3/envs/python36/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: ISOLATION_FOREST

**Comment by cdycdy666** [comment]
my env:
python: 3.6.13
pip: 21.2.2
tensorflow: 2.2.0
keras: 2.3.0

**Comment by HeGsnS** [comment]
> when i run LSTMOD_test.py
> 
> Traceback (most recent call last): File "LSTMOD_test.py", line 2, in from tods.sk_interface.detection_algorithm.LSTMODetector_skinterface import LSTMODetectorSKI File "/home/tods/tods/**init**.py", line 5, in from tods.detection_algorithm import * File "/home/tods/tods/detection_algorithm/**init**.py", line 5, in from tods.detection_algorithm.LSTMODetect import LSTMODetectorPrimitive File "/home/tods/tods/detection_algorithm/LSTMODetect.py", line 164, in class LSTMODetectorPrimitive(UnsupervisedOutlierDetectorBase[Inputs, Outputs, Params, Hyperparams]): File "/home/tods/tods/detection_algorithm/LSTMODetect.py", line 199, in LSTMODetectorPrimitive "algorithm_types": [metadata_base.PrimitiveAlgorithmType.ISOLATION_FOREST, ], # up to update File "/home/anaconda3/envs/python36/lib/python3.6/enum.py", line 326, in **getattr** raise AttributeError(name) from None AttributeError: ISOLATION_FOREST

Try to revise line 199 of LSTMODetect.py into "algorithm_types": [ metadata_base.PrimitiveAlgorithmType.TODS_PRIMITIVE, ],

We will fix this bug sooner.

**Comment by lhenry15** [comment]
Hi the problem is fixed in the dev branch, which also support python 3.7+, we will merge it to master branch soon!

**Comment by koric00** [comment]
> Hi the problem is fixed in the dev branch, which also support python 3.7+, we will merge it to master branch soon!

Same problem for me, have this issue been fixed ?

**Comment by lhenry15** [comment]
> > Hi the problem is fixed in the dev branch, which also support python 3.7+, we will merge it to master branch soon!
> 
> Same problem for me, have this issue been fixed ?

This problem is due to our recent development on our backbone package (tamu_d3m) to support Python3.7+. You may want to specify the version of tamu_d3m in setup.py as 2021.2.12. Or, you can install the version in the dev branch with Python3.7~Python3.9.2.

**Comment by koric00** [comment]
> > > Hi the problem is fixed in the dev branch, which also support python 3.7+, we will merge it to master branch soon!
> > 
> > 
> > Same problem for me, have this issue been fixed ?
> 
> This problem is due to our recent development on our backbone package (tamu_d3m) to support Python3.7+. You may want to specify the version of tamu_d3m in setup.py as 2021.2.12 (I have updated it in the master branch). Or, you can install the version in the dev branch with Python3.7~Python3.9.2.

Thank u! Worked for me after git pull

**Comment by soso-maitha** [comment]
Hello, but github is blocked in our network. I used pip install behind proxy but i cannot pull.
what should I do to resolve the error ?

**Comment by soso-maitha** [comment]
> > > Hi the problem is fixed in the dev branch, which also support python 3.7+, we will merge it to master branch soon!
> > 
> > 
> > Same problem for me, have this issue been fixed ?
> 
> This problem is due to our recent development on our backbone package (tamu_d3m) to support Python3.7+. You may want to specify the version of tamu_d3m in setup.py as 2021.2.12 (I have updated it in the master branch). Or, you can install the version in the dev branch with Python3.7~Python3.9.2.

does the package support python 3.7 now ?

**Comment by soso-maitha** [comment]
> Hi the problem is fixed in the dev branch, which also support python 3.7+, we will merge it to master branch soon!

does the package support python 3.7 now ?
