### ISSUE TITLE
AttributeError: TODS_PRIMITIVE

### ISSUE THREAD

**Issue by Dragon-zc** [datamllab/tods#50]
I encountered the following error when importing tods

Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    import tods
  File "/home /miniconda3/envs/py36/lib/python3.6/site-packages/tods-0.0.2-py3.6.egg/tods/__init__.py", line 2, in <module>
    from tods.data_processing import *
  File "/home/miniconda3/envs/py36/lib/python3.6/site-packages/tods-0.0.2-py3.6.egg/tods/data_processing/__init__.py", line 1, in <module>
    from tods.data_processing.CategoricalToBinary import CategoricalToBinaryPrimitive
  File "/home /miniconda3/envs/py36/lib/python3.6/site-packages/tods-0.0.2-py3.6.egg/tods/data_processing/CategoricalToBinary.py", line 119, in <module>
    class CategoricalToBinaryPrimitive(transformer.TransformerPrimitiveBase[Inputs, Outputs, Hyperparams]):
  File "/home /miniconda3/envs/py36/lib/python3.6/site-packages/tods-0.0.2-py3.6.egg/tods/data_processing/CategoricalToBinary.py", line 159, in CategoricalToBinaryPrimitive
    metadata_base.PrimitiveAlgorithmType.TODS_PRIMITIVE,
  File "/home /miniconda3/envs/py36/lib/python3.6/enum.py", line 324, in __getattr__
    raise AttributeError(name) from None
AttributeError: TODS_PRIMITIVE

**Comment by yzhbreeze** [comment]
I have the same problem. Have you solved it

**Comment by soso-maitha** [comment]
I am getting the same error. I am using python 3.7 on Windows 10
