### ISSUE TITLE
ModuleNotFoundError: No module named 'tods.sk_interface'

### ISSUE THREAD

**Issue by wayneking517** [datamllab/tods#63]
I believe that I did a successful install of tods.

Giving the command:

~~~from tods import generate_dataset, generate_problem
~~~

yields no error. 

but, I get an error with

~~~
from tods.sk_interface.detection_algorithm.MatrixProfile_skinterface import MatrixProfileSKI
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tods.sk_interface'~~~

I am sorry for asking such a rookie question. I suspect that the resolution to this is probably pretty easy.

**Comment by lhenry15** [comment]
Could you provide more details like python version and which branch are you using so that I can try to reproduce your error? Thanks.

**Comment by wayneking517** [comment]
Hi Henry,

 

I loaded TODS using pycharm-> preferences -> Python Interpreter -> add tods 0.0.2

 

I do not know how to give you the branch info.

 

I am running Python 3.7 on that machine.

 

 

 

From: Henry ***@***.***>
Reply-To: datamllab/tods ***@***.***>
Date: Friday, June 10, 2022 at 1:51 PM
To: datamllab/tods ***@***.***>
Cc: Wayne King ***@***.***>, Author ***@***.***>
Subject: Re: [datamllab/tods] ModuleNotFoundError: No module named 'tods.sk_interface' (Issue #63)

 

Could you provide more details like python version and which branch are you using so that I can try to reproduce your error? Thanks.

**Comment by hwy893747147** [comment]
Hi @wayneking517 

I will try to help you as much as possible, first, when you use a "Python Interpreter" and added "Tods 0.0.2" does that mean this is the environment that you successfully installed TODS in?

Second, to check your branch after you cloned this repo, you can type "git branch" in the terminal. By default, you will be on the "master" branch. 

Also, have you checked out the demo notebook where you can reproduce the exact same steps to setup TODS after you clone the repo into your local environment. 

The notebook can be found at: https://colab.research.google.com/drive/1oKKRqAQnkATsALffaf54zkDGpRseNVGZ?usp=sharing

Please let me know more details to better help you.
Thanks,
-Wangyang
