### ISSUE TITLE
ImportError: pycurl: libcurl link-time version (7.69.1) is older than compile-time version (7.73.0)

### ISSUE THREAD

**Issue by HeGsnS** [datamllab/tods#9]
I got 'ImportError: pycurl: libcurl link-time version (7.69.1) is older than compile-time version (7.73.0)' when execute 'from axolotl.utils import data_problem'.

**Comment by HeGsnS** [comment]
Reduce the version of pycurl to 7.43.0.2 (the default installed version is 7.43.0.5).

**Comment by genius0182** [comment]
from d3m import index error
I got 'ImportError: pycurl: libcurl link-time version (7.58.0) is older than compile-time version (7.68.0)'
I used pycurl==7.43.0.6

**Comment by HeGsnS** [comment]
> from d3m import index error
> I got 'ImportError: pycurl: libcurl link-time version (7.58.0) is older than compile-time version (7.68.0)'
> I used pycurl==7.43.0.6

Degrad pycurl to 7.43.0.2, if it still not work, try to degrad to earlier version.
BTW, the contributors are trying to make TODS not depend on pycurl, new version TODS won't have this issue.

**Comment by genius0182** [comment]
@HeGsnS I try to pycurl to 7.43.0 ,it still not work.

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/workspace/lh/git_worksapce/tods/src/d3m/d3m/index.py", line 21, in <module>
    import pycurl  # type: ignore
ImportError: pycurl: libcurl link-time version (7.58.0) is older than compile-time version (7.68.0)
python-BaseException
