### ISSUE TITLE
AttributeError:  ANOMALY_DETECTION

### ISSUE THREAD

**Issue by jozef507** [datamllab/tods#95]
Hey. I have this issue with tods:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from tods.detection_algorithm import PyodCBLOF
  File "/home/user/.local/lib/python3.7/site-packages/tods/detection_algorithm/PyodCBLOF.py", line 116, in <module>
    class CBLOFPrimitive(UnsupervisedOutlierDetectorBase[Inputs, Outputs, Params, Hyperparams]):
  File "/home/user/.local/lib/python3.7/site-packages/tods/detection_algorithm/PyodCBLOF.py", line 204, in CBLOFPrimitive
    "primitive_family": metadata_base.PrimitiveFamily.ANOMALY_DETECTION,
  File "/usr/lib/python3.7/enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: ANOMALY_DETECTION

I installed tods with command `pip install tods` on Ubuntu 22.04.2 LTS

I have installed:
- python 3.7.16
- pip 22.0.2

Installed packages:
absl-py                      1.4.0
apturl                       0.5.2
astunparse                   1.6.3
attrs                        23.1.0
backports.zoneinfo           0.2.1
bcrypt                       3.2.0
blinker                      1.4
Brlapi                       0.8.3
cachetools                   5.3.0
caffeine                     2.9.8
certifi                      2020.6.20
chardet                      4.0.0
chrome-gnome-shell           0.0.0
click                        8.0.3
colorama                     0.4.4
command-not-found            0.3
cryptography                 3.4.8
cupshelpers                  1.0
custom-inherit               2.3.2
cx-Oracle                    8.3.0
cycler                       0.11.0
d3m                          2022.5.5
dateparser                   1.1.8
dbus-python                  1.2.18
decorator                    5.1.1
defer                        1.0.6
distro                       1.7.0
distro-info                  1.1build1
duplicity                    0.8.21
event-bus                    1.0.2
ewmh                         0.1.6
fasteners                    0.14.1
Flask                        2.0.2
flatbuffers                  2.0.7
fonttools                    4.38.0
frozendict                   1.2
future                       0.18.2
gast                         0.4.0
gevent                       21.8.0
gitdb                        4.0.10
GitPython                    3.1.31
google-auth                  2.17.3
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
gpg                          1.16.0-unknown
GPUtil                       1.4.0
greenlet                     1.1.2
grpcio                       1.54.0
h5py                         3.8.0
httplib2                     0.20.2
idna                         3.3
importlib-metadata           4.8.2
itsdangerous                 2.0.1
jeepney                      0.7.1
Jinja2                       3.0.3
joblib                       1.2.0
jsonpath-ng                  1.5.3
jsonschema                   4.0.1
keras                        2.7.0
Keras-Preprocessing          1.1.2
keyring                      23.5.0
kiwisolver                   1.4.4
language-selector            0.1
launchpadlib                 1.10.16
lazr.restfulclient           0.14.4
lazr.uri                     1.0.6
liac-arff                    2.5.0
libclang                     16.0.0
llfuse                       1.3.8
llvmlite                     0.39.1
lockfile                     0.12.2
louis                        3.20.0
macaroonbakery               1.3.1
Markdown                     3.4.3
MarkupSafe                   2.0.1
matplotlib                   3.5.3
monotonic                    1.6
more-itertools               8.5.0
mypy-extensions              1.0.0
netifaces                    0.11.0
nimfa                        1.4.0
numba                        0.56.4
numpy                        1.18.2
oauthlib                     3.2.0
olefile                      0.46
openml                       0.11.0
opt-einsum                   3.3.0
packaging                    23.1
pandas                       1.3.5
paramiko                     2.9.3
patsy                        0.5.3
pexpect                      4.8.0
Pillow                       7.1.2
pip                          22.0.2
ply                          3.11
protobuf                     3.12.4
ptyprocess                   0.7.0
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycairo                      1.20.1
pycryptodomex                3.11.0
pycups                       2.0.1
pyeventbus3                  0.10
Pygments                     2.11.2
PyGObject                    3.42.1
PyJWT                        2.3.0
pymacaroons                  0.13.0
pymongo                      4.0
PyNaCl                       1.5.0
pyod                         1.0.0
pyOpenSSL                    21.0.0
pyparsing                    2.4.7
pyRFC3339                    1.1
pyrsistent                   0.18.1
python-apt                   2.4.0+ubuntu1
python-dateutil              2.8.1
python-debian                0.1.43ubuntu1
python-xlib                  0.29
pytypes                      1.0b10
pytz                         2023.3
pytz-deprecation-shim        0.1.0.post0
PyWavelets                   1.3.0
pyxattr                      0.7.2
pyxdg                        0.27
PyYAML                       5.4.1
regex                        2022.10.31
requests                     2.25.1
requests-oauthlib            1.3.1
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rsa                          4.9
scikit-learn                 0.22
scipy                        1.7.3
screen-resolution-extra      0.0.0
SecretStorage                3.3.1
selenium                     3.141.0
setuptools                   59.6.0
simplejson                   3.12.0
six                          1.16.0
smmap                        5.0.0
statsmodels                  0.11.1
stumpy                       1.4.0
systemd-python               234
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.7.4
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.32.0
termcolor                    2.3.0
tods                         0.0.2
typing_extensions            4.0.1
typing-inspect               0.7.1
tzdata                       2023.3
tzlocal                      4.3
ubuntu-advantage-tools       8001
ubuntu-drivers-common        0.0.0
ufw                          0.36.1
unattended-upgrades          0.1
urllib3                      1.26.5
usb-creator                  0.3.7
vboxapi                      1.0
wadllib                      1.3.6
webcolors                    1.11.1
Werkzeug                     2.0.2
wheel                        0.37.1
wrapt                        1.15.0
xdg                          5
xkit                         0.0.0
xmltodict                    0.13.0
youtube-dl                   2021.12.17
zipp                         3.6.0
zope.event                   4.5.0
zope.interface               5.4.0

I even tried run in docker with python3.7/python3.8 and issue is the same.

**Comment by jozef507** [comment]
Isuue solved. Just neede install it by installation guide that is here on github. Dont install it with "pip install tods"
